### ISSUE TITLE
ScrollToFixed generating extra div problem

### ISSUE THREAD

**Issue by danny-faith** [bigspotteddog/ScrollToFixed#10]
Hi, firstly I'd like to say that the plugin is great and thank you ver much for sharing.

However I am having a slight problem with it, I have seem to be having an extra div being generated when jthe function assigns the 'fixed' position attribute.

You can takek a look at the problem here: http://faiththeagency.com/easyphone/frequently-asked-questions.php

Not sure if anyone else has had this problem at all?

Could someone please help?

**Comment by ifarooq** [comment]
The below one worked for me. 

//Scroll to fixed sidebar
  $("#fixed-sidebar-wrapp").scrollToFixed();
  //Remove extra div
  $("#fixed-sidebar-wrapp").next().remove();
