### ISSUE TITLE
limit with css class not working

### ISSUE THREAD

**Issue by nviror** [bigspotteddog/ScrollToFixed#172]
I have tried with different classes and IDs in the footer but the fixed sidebar element  doesn't stop scrolling to the .footer class. The issue is live on this website http://goo.gl/Rzyfei

There are two more subjects below "Political Science" but they are hidden.

Screenshot: http://i.imgur.com/NRpKglg.png

**Comment by monzanovending** [comment]
A couple of suggestions:

1. The limit is actually applied at the top of the target element, so you have to deduct the height of the target to get the limit to kick in when the footer touches the bottom. Deduct for some padding too.

2. The target will most likely jump out of position when the limit kicks in as it appears that the target is not in a container that will hold its position. Try the removeOffsets option. If that does not work, put the target in a div that stays in place.

3. If you have any dynamic content, I like to use the limit as a function. Wrapping the limit in a function causes it to recalculate each time it is evaluated in case heights change.

Good luck!

**Comment by nviror** [comment]
Thanks @monzanovending  If you could provide a code sample It would help me get your suggestion better. The current relevant code is as follows

FOOTER
```
<div style="text-align:right" class="row footer">
			<p class="site_logo"><span style="color:#2431D2">Syllabus</span><span style="color:#1EBF0D">Man</span><span style="color:#999999">.com</span></p>
</div>
```
JS
```
$(document).ready(function() {

  $('.fixed').scrollToFixed({
	marginTop: 10,
	limit: $('.footer').offset().top
  });
  
});
```

**Comment by nviror** [comment]
Thanks a lot @monzanovending 

1. Done
2. removeOffsets worked.
3. Not dynamic

Could you please check the result?

**Comment by bigspotteddog** [comment]
@nviror The results look good. To reduce that jump when the limit kicks in, make the .three.column position: relative. Nice work!

I am actually @monzanovending too; I was logged into a client account.

**Comment by nviror** [comment]
Just wanted to say, you're awesome @bigspotteddog :)

**Comment by bigspotteddog** [comment]
Thanks!
