### ISSUE TITLE
Vertical scrollbar issue

### ISSUE THREAD

**Issue by jitowix** [bigspotteddog/ScrollToFixed#175]
I have an element centered and fixed on my page.
The issue is if a vertical scrollbar is added or removed (when new content is loaded for example), the element isn't centered anymore (by a few pixels, equals to the scrollbar width).

Maybe we should detect when a vertical scrollbar is added/removed, but I don't know if it's possible.

**Comment by bigspotteddog** [comment]
When dynamic content is loaded, call window.resize(). That will cause the plugin to recalculate its position. Good luck!

**Comment by jitowix** [comment]
Thank you!!
