### ISSUE TITLE
Not working on a sidebar widget

### ISSUE THREAD

**Issue by srikat** [bigspotteddog/ScrollToFixed#176]
When I run the script on a horizontal element like header or primary nav in my WordPress site, it works fine.

But when I do to make a sidebar widget fixed via `$('#text-4').scrolltofixed();`, it doesn't work.

There is an error in console: http://d.pr/i/1clOh. This error does not come up when I do it on a horizontal element like so: `$('.nav-primary').scrollToFixed();`

Any ideas?

**Comment by bjwang** [comment]
I didn't see the plugin in ScrollToFixed page！Can you test?
You can refer to this example！  http://jsfiddle.net/y3qV5/434/

**Comment by srikat** [comment]
@bjwang Not sure whether you wanted to reply to my post. I have not provided any URL of the site/page where I have this running.

Yes, I saw that example and it is working fine.

**Comment by srikat** [comment]
Operator error.

Suggestion: It would be nice to make the fixed element automatically get the width that it had before it was fixed.

**Comment by bigspotteddog** [comment]
That is a good suggestion. I will check it out when I have a chance. Best of luck!
