### ISSUE TITLE
iOS Safari, plugin adds div with extra height

### ISSUE THREAD

**Issue by MikeTheVike** [bigspotteddog/ScrollToFixed#179]
If you visit http://globe.5byfivecreative.com/office-space, below the sub menu you will see the blue area that says "Offices with No Speed Limit". As soon as you scroll the plugin adds a div with a height set in px that drops everything down. I have minWidth set (see screenshot) so that nothing should become sticky when the device width is < 650px. It seems to work fine on other mobile browsers like Chrome, but Safari has issues. Any idea why this is happening and can it be fixed? Am I implementing it incorrectly? Thanks for any help!

![screen shot 2015-03-17 at 3 13 11 pm](https://cloud.githubusercontent.com/assets/220292/6696547/3114e2f8-ccb8-11e4-9a45-ab13762f7c59.png)

**Comment by bigspotteddog** [comment]
Take a look at the spacerClass option. With this you can style that extra div (spacer) to effectively remove it.

**Comment by MikeTheVike** [comment]
That did it! Thanks for the super quick response!
