### ISSUE TITLE
Bootstrap 3, Width Column Decreased

### ISSUE THREAD

**Issue by ghprod** [bigspotteddog/ScrollToFixed#180]
Hi :)

I have some column, when scroll to fixed isnt active, then there's no problem, width of column still normal

![image](https://cloud.githubusercontent.com/assets/1922652/6847854/187eeaf4-d3fc-11e4-91a2-417eb44d6dba.png)

But when its scroll to down, width of element start decreased

![image](https://cloud.githubusercontent.com/assets/1922652/6847865/360f4a6e-d3fc-11e4-9d6b-82ed0fac8b72.png)

Any Idea how to fix this?

Thanks :)

**Comment by ghprod** [comment]
Ah seems like i solved this problem, so to make this working, you cant use class thats same level with ``col-x-x`` as selector for scrollToFixed, but you need to create parent class inside ``col-x-x`` and use that for scrollToFixed selector :+1: 

![image](https://cloud.githubusercontent.com/assets/1922652/6848152/2bbc8890-d3fe-11e4-914e-e27a5df3cdfe.png)

Thanks ..case closed .. :+1:

**Comment by bigspotteddog** [comment]
Excellent work! Thank you for sharing the solution!
