### ISSUE TITLE
ScrollToFixed not stopping at bottom

### ISSUE THREAD

**Issue by Hiro-Protagonist** [bigspotteddog/ScrollToFixed#181]
This is working great in almost every respect, but when it gets to the limit it still scrolls past it!  Any ideas?

**Comment by mwhaynes** [comment]
I'm seeing the same problem. When the page is scrolled my sidebar continues to scroll over the footer. You can view this at:   http://www.abilityconnectiontexas.org/testlayout_2column.php 

Calls to jquery and scrolltofixed in the <head>:

    <script src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery-scrolltofixed.js"></script>

javascript document.ready function: 
	<script type="text/javascript">
		$(document).ready(function(){
			$('.mmenu').scrollToFixed(); //mmenu is the class of the div that contains the nav bar
			$('.floatMe').scrollToFixed({  //floatMe is the class of the div that is to scroll in the left sidebar
				marginTop: $('.mmenu').outerHeight() + 10,
				limit: $('.footerbuffer').offset().top - $('.floatMe').outerHeight() - 10,
				minWidth: 640,
				zIndex: 999,
			});
			$('.footerbuffer').scrollToFixed( { //footerbuffer is the class of the div just above the footer.
				bottom: 0,
				limit: $('.footerbuffer').offset().top,
			});
	</script

layer stack:
<div id="outerWrapper">
	<div id="toprowbkgnd"> 	   
		<div id="toprow" class="row">	
			...content...
		</div>
	</div>
	<div id="pre-header" class="row">
		...content...  
	</div>
	<div id="nav" class="mmenu" style="margin-left: 0; margin-right: 0; max-width: 100%;">
 	   	<div class="row" style="height: auto;">
		    	<div class="large-12 columns">
		        	...nav bar content...			
		        </div>
	        </div>
	</div>
	<div id="contentWrapper">   
		<div id="content" class="row">
			<div class="large-12 columns">
				<div class="panel">
					<div class="large-4 medium-4 columns">
						<div class="floatMe" id="sidebar">
							...sidebar content...
						</div>
					</div>
					<div class="large-8 medium-8 columns">
						...main page content...
					</div>
						<div id="map-container">
							<div id="loc-list">
								...map list...
							</div>
							<div id="map"></div>
						</div>
						<div class="clearfix"></div>	        
				</div>
			</div>
		</div>
	</div>
	<div class="sponsorWrapper">
		...sponsor content...
	</div>     
	<div class="footerbuffer"></div>
	<div class="footerwrapper">
		...footer content...
	</div>
</div>

I've reproduced the code in the page at:
http://jsfiddle.net/ZczEt/167/
and it is working for me. I suspect there's something on my page that's conflicting with the script that enables the limit but haven't been able to spot it. I hope  you can see what's causing the problem so that I can get this feature implemented quickly. 

Much thanks for your help!
enthusiastically, 
mwhaynes

**Comment by bigspotteddog** [comment]
Please post the code for the scroll to fixed call so I can more easily see what is being set. Thanks!

**Comment by mwhaynes** [comment]
Sorry I tried posting the code in my previous message. Here it is again:

Calls to jquery and scrolltofixed in the <head>:

    <script src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery-scrolltofixed.js"></script>

javascript document.ready function: 
	<script type="text/javascript">
		$(document).ready(function(){
			$('.mmenu').scrollToFixed();
			$('.floatMe').scrollToFixed({
				marginTop: $('.mmenu').outerHeight() + 10,
				limit: $('.sponsorWrapper').offset().top - $('.floatMe').outerHeight() - 10,
				minWidth: 640,
				zIndex: 999,
			});
			$('.footerbuffer').scrollToFixed( {
				bottom: 0,
				limit: $('.footerbuffer').offset().top,
			});
	</script>

I'll include the div stack in my next post....

**Comment by mwhaynes** [comment]
Here's the <div> stack on the page:
<div id="outerWrapper">
	<div id="toprowbkgnd"> 	   
		<div id="toprow" class="row">	
			...content...
		</div>
	</div>
	<div id="pre-header" class="row">
		...content...  
	</div>
	<div id="nav" class="mmenu" style="margin-left: 0; margin-right: 0; max-width: 100%;">
 	   	<div class="row" style="height: auto;">
		    	<div class="large-12 columns">
		        	...nav bar content...			
		        </div>
	        </div>
	</div>
	<div id="contentWrapper">   
		<div id="content" class="row">
			<div class="large-12 columns">
				<div class="panel">
					<div class="large-4 medium-4 columns">
						<div class="floatMe" id="sidebar">
							...sidebar content...
						</div>
					</div>
					<div class="large-8 medium-8 columns">
						...main page content...
					</div>
						<div id="map-container">
							<div id="loc-list">
								...map list...
							</div>
							<div id="map"></div>
						</div>
						<div class="clearfix"></div>	        
				</div>
			</div>
		</div>
	</div>
	<div class="sponsorWrapper">
		...sponsor content...
	</div>     
	<div class="footerbuffer"></div>
	<div class="footerwrapper">
		...footer content...
	</div>
</div>

**Comment by mwhaynes** [comment]
Hi Big:

 

I seem be having some problem getting my code to display on the GitHub form. Here is the code: 

 

 

Calls to jquery and scrolltofixed in the <head>:

 

    <script src="js/jquery.min.js"></script>

    <script type="text/javascript" src="js/jquery-scrolltofixed.js"></script>

 

javascript document.ready function: 

                <script type="text/javascript">

                                $(document).ready(function(){

                                                $('.mmenu').scrollToFixed();

                                                $('.floatMe').scrollToFixed({

                                                                marginTop: $('.mmenu').outerHeight() + 10,

                                                                limit: $('.sponsorWrapper').offset().top - $('.floatMe').outerHeight() - 10,

                                                                minWidth: 640,

                                                                zIndex: 999,

                                                });

                                                $('.footerbuffer').scrollToFixed( {

                                                                bottom: 0,

                                                                limit: $('.footerbuffer').offset().top,

                                                });

                </script

 

layer stack:

<div id="outerWrapper">

                <div id="toprowbkgnd">                 

                                <div id="toprow" class="row"> 

                                                ...content...

                                </div>

                </div>

                <div id="pre-header" class="row">

                                ...content...  

                </div>

                <div id="nav" class="mmenu" style="margin-left: 0; margin-right: 0; max-width: 100%;">

                               <div class="row" style="height: auto;">

                                                <div class="large-12 columns">

                                                ...nav bar content...                                        

                                        </div>

                        </div>

                </div>

                <div id="contentWrapper">   

                                <div id="content" class="row">

                                                <div class="large-12 columns">

                                                                <div class="panel">

                                                                                <div class="large-4 medium-4 columns">

                                                                                                <div class="floatMe" id="sidebar">

                                                                                                                ...sidebar content...

                                                                                                </div>

                                                                                </div>

                                                                                <div class="large-8 medium-8 columns">

                                                                                                ...main page content...

                                                                                </div>

                                                                                                <div id="map-container">

                                                                                                                <div id="loc-list">

                                                                                                                                ...map list...

                                                                                                                </div>

                                                                                                                <div id="map"></div>

                                                                                                </div>

                                                                                                <div class="clearfix"></div>                

                                                                </div>

                                                </div>

                                </div>

                </div>

                <div class="sponsorWrapper">

                                ...sponsor content...

                </div>     

                <div class="footerbuffer"></div>

                <div class="footerwrapper">

                                ...footer content...

                </div>

</div>

 

As I mentioned in my post, you can view this at:

 

http://www.abilityconnectiontexas.org/testlayout_2column.php 

 

Thank you for your help!!!

 

 

Enthusiastically, 

 

 

 

Follow us online at:   <http://www.facebook.com/home.php#!/pages/Ability-Connection-Texas-ACT/127447367301848>     <http://twitter.com/#!/AbilityTexas> 

Mark Haynes 
Community/e-Philanthropy Manager 

Ability Connection Texas

Direct: 214-247-4504

Cell: 469-426-4889 

Fax: 214-351-2610

Email: MHaynes@AbilityConnectionTexas.org

Website: www.abilityconnectiontexas.org <http://www.abilityconnectiontexas.org/> 

 

Ability Connection Texas Email Disclaimer www.abilityconnectiontexas.org <http://www.abilityconnectiontexas.org/email_disclaimer.php> 

 

P Please consider the environment before printing this email.

**Comment by mwhaynes** [comment]
p.s. You’ll notice that I use the minWidth property to disable the ScrollToFixed feature when viewing on a browser screen that is under 640 pixels wide. 

 

Thanks again!!!

 

Enthusiastically, 

 

 

 

Follow us online at:   <http://www.facebook.com/home.php#!/pages/Ability-Connection-Texas-ACT/127447367301848>     <http://twitter.com/#!/AbilityTexas> 

Mark Haynes 
Community/e-Philanthropy Manager 

Ability Connection Texas

Direct: 214-247-4504

Cell: 469-426-4889 

Fax: 214-351-2610

Email: MHaynes@AbilityConnectionTexas.org

Website: www.abilityconnectiontexas.org <http://www.abilityconnectiontexas.org/> 

 

Ability Connection Texas Email Disclaimer www.abilityconnectiontexas.org <http://www.abilityconnectiontexas.org/email_disclaimer.php> 

 

P Please consider the environment before printing this email.

**Comment by bigspotteddog** [comment]
Try putting the limit in a function. Similar to the "very full" example on the main project page. If dynamic content is loaded anywhere on the page that changes the offsets on the page, a limit function will correct the issue.

**Comment by bigspotteddog** [comment]
I just tried it. It did not work for me. Must be something else.

**Comment by mwhaynes** [comment]
So putting the limit in a function did not work? I'll play around with it and let you know what I get. There is some dynamic content being pulled from a MySQL database. I'm using MySQLi queries, but I don't know if that's the cause of the problem. I've probably got a semicolon out of place somewhere. ;~}

**Comment by mwhaynes** [comment]
Perhaps if we back up and look at the LIMIT option. The documentation says:
limit (value|function) - the vertical scroll position at which the element will begin to scroll up the page (absolutely).
This would appear to be a location on the vertical scroll where the fixed element converts to an absolute positioned element. I've tested with various values, both positive and negative by changing the -10 to see how that affects the positioning and nothing seems to be working. I've also tried removing the "$('.footerbuffer').offset().top" leaving just a numerical value and when I scroll down, instead of stopping, the fixed element jumps down and to the right. See:
http://www.abilityconnectiontexas.org/testlayout_2column_b.php 

Perhaps what happens when we use an absolute value will give us a clue as to what's going on.

Meanwhile, I read in a comment on a similar script that the fixed div must be sibling of the div used to set the limit value. I tested this by nesting five levels of divs inside the footerbuffer and referencing the innerdiv:   $('.fifthlevel').offset().top but that did not work. Do you have any other ideas? 

Thanks for your help!

**Comment by bigspotteddog** [comment]
I will pull down the site when I get a chance so I can debug and manipulate it locally. I am maintaining this component on the side. It might take me a bit. Sorry for the inconvenience.

**Comment by bigspotteddog** [comment]
Try this (removeOffsets: true seemed to do the trick):

    $('.floatMe').scrollToFixed({
        marginTop: $('.mmenu').outerHeight() + 10,
        limit: function () {
            return $('.sponsorWrapper').offset().top - $('.floatMe').outerHeight() - 10;
        },
        minWidth: 640,
        zIndex: 999,
        removeOffsets: true
    });

**Comment by mwhaynes** [comment]
Thanks Matt, that did it. I was concerned that the limit setting was not working because when I wrote the values to vars and then writing those values to the page:  I was able to get proper numbers

    	<div class="sponsorBuffer"><hr>
        	<p id="demo"></p>
               <script>
	                var $myLimit=$('.sponsorBuffer').offset().top;
                    var $floatSide=$('.floatMe').outerHeight();
                    var $difference=$myLimit - $floatSide;
	                document.getElementById("demo").innerHTML = $difference;
              	</script>  
        </div>

and when I used 
limit: $difference - 10, 
I still wasn't getting the desired result. putting the limit into a function and including removeOffsets: true fixed the problem for me. 

Thanks so much!

**Comment by bigspotteddog** [comment]
Glad it worked. You are welcome! My name is Joseph :) Best of luck to you!

**Comment by mwhaynes** [comment]
Sorry Joseph! You can view the results at our website at http://www.abilityconnectiontexas.org. Check out the slider images on the home page. they use a position aware hover effect to follow your cursor as you move it over each image.

**Comment by bigspotteddog** [comment]
That is awesome! I love what you are doing!
