### ISSUE TITLE
Show Footer only when first scrolling down

### ISSUE THREAD

**Issue by achimbaur** [bigspotteddog/ScrollToFixed#192]
I am trying to NOT show the footer initially. Ideally it would appear from the bottom of the screen once a user first scrolls down. Can this be done?

**Comment by bigspotteddog** [comment]
Hmmm... On first scroll, you can have a script (separate from the plugin) check the scroll position and set the display style on the footer.

If you want the user to scroll down to the bottom then reveal the footer, this is in the reveal example.

I think you want the former. I would go with a script. The plugin does not really handle that case.

Good luck!

**Comment by achimbaur** [comment]
Thanks!
