### ISSUE TITLE
Window load

### ISSUE THREAD

**Issue by furyscript** [bigspotteddog/ScrollToFixed#194]
Hi all,

I've a problem with my directive this is the code:
```javascript
MayApp.directive('scrolly', ['$rootScope', '$timeout', function($rootScope, $timeout) {  
    return {
        restrict: 'A',
        link: function($scope, $element, $attrs) {
            $(window).load(function() {
                $element.scrollToFixed({
                    marginTop: 55
                });
            });
            $rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
                event.targetScope.$watch("$viewContentLoaded", function() {
                    $element.scrollToFixed({
                        marginTop: 55
                    });
                });
            });
        }
    };
}]);
```
The problem is that: When I enter in the page  or I refresh it, the plugin (scrollToFixed) works fine. When I enter in the page from state the code not work (there isn't load event and also the $stateChangeSuccess not work, I see that event is fired but not apply scrollToFixed)

Have you a solution? 
I use ui-router

Thanks

**Comment by bigspotteddog** [comment]
From the event code you can call window.scroll() to get the plugin to recalculate. That might correct the issue.

**Comment by furyscript** [comment]
But if I delete window.load "scrollToFixed" not works fine because I need to wait DOM loaded before call your plugin.

**Comment by furyscript** [comment]
It is working call "window.scroll()" to recalculate,I hope this is stable fix for all...
Although rendering is not quite accurate..

**Comment by bigspotteddog** [comment]
It is possible that the plugin is already loaded and returns the instance it knows of without doing anything. You can detach scroll to fixed then reapply it in your event code, rather than calling window.scroll. Window.scroll is stable and it is what happens every time the window is scrolled.

**Comment by bigspotteddog** [comment]
Detach like this:

$('.header').trigger('detach.ScrollToFixed');

**Comment by furyscript** [comment]
So can you confirm me that window.scroll trigger the scrollToFixed and is it stable??
Actually I use this "workaround" but it works.

**Comment by bigspotteddog** [comment]
Yes, it is stable.

**Comment by furyscript** [comment]
Thank you!
