### ISSUE TITLE
Missing 1.0.7 release

### ISSUE THREAD

**Issue by przem** [bigspotteddog/ScrollToFixed#201]
As in subject, please release 1.0.7 version so it can be used with bower.
It contains a crucial fix desperately needed :)

Thanks in advance

**Comment by bigspotteddog** [comment]
I will get this out as soon as I can. Thanks!

**Comment by jonnott** [comment]
Seems to have been some useful changes since last official 1.0.6 release .. can a new release be tagged soon?

**Comment by bigspotteddog** [comment]
Updated to version 1.0.8.
