### ISSUE TITLE
How to use triggers? Specifically  $(window).resize();

### ISSUE THREAD

**Issue by Mahnie** [bigspotteddog/ScrollToFixed#210]
Awesome plugin - Thank you so much! Quick question though ... I see in the trigger section you say:

```
 $(window).resize(); // Causes the plugin to recalculate the element offsets, then the window scroll.
                      // Good for layout changes that could cause the fixed element to move.
                      // Example: the header height increases which should cause the fixed
                      // element to fix at a greater vertical scroll position.
```

However, forgive me but ... I don't know how or where to implement that?

My code is:

```
$(document).ready(function() {
    	  $('#trip-tabs').scrollToFixed({
    	          marginTop: $('.header').outerHeight(),
     	      });
    	});
```

Where do I add  `$(window).resize();` ??

Thanks in advance for your help!

**Comment by bigspotteddog** [comment]
You add that call anywhere dynamic changes to the layout occur that may effect the fixed element. For example, if you dynamically add a new element, or resize content inside of the fixed element, that causes the fixed element to need to respond to the change, call $(window).resize().

**Comment by Mahnie** [comment]
Well it is a responsive site. So, every time the window is resized the header height might change. And if you see by my code, I'm having my fixed tabs with a margin top equal to the header height. So ... Can you edit my code to show me how I would account for the header height changing on resize please? Thank you so much!!

**Comment by bigspotteddog** [comment]
If the window resizes, nothing needs to be done. The resize event is automatically picked up by the plugin. Calling $(window).resize is only needed when you add or resize content programmatically.

**Comment by Mahnie** [comment]
Interesting, because it doesn't work on resize.  See site at https://www.backroads.com/trips/BMTI. Once you scroll, the tabs stay below the header. If you resize to smaller you see a gap appear as the header becomes less tall, if you resize to tablet size you'll see the tabs disappear altogether as the header gets tall and the tabs are hidden behind it. Any advice??

**Comment by bigspotteddog** [comment]
Ah, the header is changing heights depending on the media query. Make marginTop a function that returns what you have in there now. The plugin is initialized with the marginTop set to initial height of the header. Making marginTop a function will cause it to re-evaluate every time the window resizes.

**Comment by bigspotteddog** [comment]
This:

    $(document).ready(function() {
      $('#trip-tabs').scrollToFixed({
        marginTop: function() {
          return $('.header').outerHeight();
        }
      });
    });

**Comment by Mahnie** [comment]
Awesome - that worked! Thank you so much for your time. :)

**Comment by bigspotteddog** [comment]
Glad it worked!

**Comment by silvio-e** [comment]
Ah, awesome, had a similar issue! Thanks a lot for asking @Mahnie and thanks a lot for answering @bigspotteddog ! :)

Have a wonderful day! :)
