### ISSUE TITLE
cssOptions is not defined

### ISSUE THREAD

**Issue by abdullah** [bigspotteddog/ScrollToFixed#216]
The source of the problem : [L148](https://github.com/bigspotteddog/ScrollToFixed/blob/master/jquery-scrolltofixed.js#L148) 

I fixed the problem by adding **cssOptions** a "var" tag.

**Comment by bigspotteddog** [comment]
Thanks for letting me know. I will make the same correction.

**Comment by phalvinayak** [comment]
@grawl I'm still getting this issue.  Also i cannot see var tag in the code.
![scrolltofix](https://cloud.githubusercontent.com/assets/230028/18024195/49346b14-6c22-11e6-9049-fabd636d1b9e.png)

**Comment by Grawl** [comment]
@phalvinayak first, I think about you are using not updated minified file, but I don't see `.min.js` in the file extension, so you probably using wrong version of ScrollToFixed.

**Comment by phalvinayak** [comment]
@Grawl, I'm using scrollToFixed from npm repository. Please have a look at the below screenshot.
![screenshot_6](https://cloud.githubusercontent.com/assets/230028/18034426/4714b5f8-6d5a-11e6-80fa-13d49ed8cd92.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/230028/18034427/4d590040-6d5a-11e6-9b1f-60d43d64f6d3.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/230028/18034430/5264544a-6d5a-11e6-810f-ac0b546d3ddc.png)

Please let me know what wrong I'm doing.

**Comment by Grawl** [comment]
@phalvinayak if you want to use my fixes now, you should use [my fork](https://github.com/Grawl/ScrollToFixed/), i.e. `npm i Grawl/ScrollToFixed` instead of `npm i ScrollToFixed` from npm repository. Because [ScrollToFixed](https://www.npmjs.com/package/scrolltofixed) package on npm is using @bigspotteddog repository, not mine. When [my PR](https://github.com/bigspotteddog/ScrollToFixed/pull/221) will be merged into this repository, my changes will be available on npm package. (I think we have to update it's version to allow npm install new version as update.)

**Comment by abdullah** [comment]
@phalvinayak  Yes, I read @Grawl's commet, this is true when this repo will updated by @bigspotteddog  on npm. You can use it.

**Comment by phalvinayak** [comment]
Thanks @Grawl that worked for me.

**Comment by phalvinayak** [comment]
@Grawl You fixes worked for me in one scenario, but there's one more place where we need `var` key word on line [#L179](https://github.com/Grawl/ScrollToFixed/blob/master/jquery-scrolltofixed.js#L179) can you please make the changes and make it up such that I can use it from the npm registry.

This scenario comes into picture when fixed content has to start scrolling along with the content. Thanks in advance.

**Comment by Grawl** [comment]
@phalvinayak actually you can make a PR to my fork and I will merge it 😄 but okay I'll just make it myself, again.

Go get it.

> make it up such that I can use it from the npm registry

With npm you can install any git repository with `package.json`, or even install by GitHub `username/repo` as I [mentioned above](https://github.com/bigspotteddog/ScrollToFixed/issues/216#issuecomment-243023391)

**Comment by phalvinayak** [comment]
Thanks @Grawl, that info was very helpful.
