### ISSUE TITLE
Scrolltofixed Div is just disappearing not scrolling

### ISSUE THREAD

**Issue by helenmarie123** [bigspotteddog/ScrollToFixed#53]
Hello, 

I think this is a fantastic feature :-) but I am having an issue with it just simply disappearing rather than scrolling up when it hits the limit point?

Also, I am wanting it to start scrolling when the bottom of the fixed div hits the limit point, where as at the moment it activates when the top of the div hits the limit point? 
Could you possibly help me with this?

Here is a link to a page where I am using it:

http://www.vision-guitars.co.uk/Yamaha-Pacifica-120H-Electric-Guitar-Black

Thank you
Helen

**Comment by dwenaus** [comment]
i'm having the same problem. it's because the left: value should be 0 but it's 1000+. Is there anyway the class could change from 'scroll-to-fixed-fixed' to 'scroll-to-fixed-absolute'?

**Comment by astralis** [comment]
I am also having the same issue. Like in the original post, the target is written above the "box" but I move it below the box via css. When the box hits the target, the box disappears.

To see what I'm trying to accomplish, similar to the original author, you can see the "Read Next" section on this page: http://www.wired.co.uk/news/archive/2015-04/30/nasa-morphing-airc
