### ISSUE TITLE
ScrollToFixed overlaps 

### ISSUE THREAD

**Issue by DashDesign** [bigspotteddog/ScrollToFixed#78]
Hello, I have a little problem with ScrollToFixed plugin.
The point is, when I chose any options from right bar Kategorier and then scroll down, this  panel overlaps my footer. There is example and script: http://dash.com.pl/CTP/gallery.html
Do You know what is wrong?
$(document).ready(function() {
    $('.sidebar').scrollToFixed({
        marginTop: 0,
        limit: $('.footer').offset().top - $('.sidebar').height() - 20  
 });
});

**Comment by carmolim** [comment]
I'm having a similar problem, but I'm calling the
```
 $(window).resize();
```

in this function:

```
$container.isotope('on', 'layoutComplete', function() {
    $(window).trigger('layoutComplete');
    $(window).resize();
});
```

link: http://wikimaki.com.br/cardapio
