### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by avclark** [bigspotteddog/ScrollToFixed#8]
Great plugin. I'm new to jQuery so this may be a simple question. Is it possible to modify a different div when the targeted div position becomes fixed?

For example, say I wanted to change the body bg color when the target div becomes fixed. Is that possible?

Thanks.

**Comment by estebandinamarca** [comment]
This method is not working for me. I just want to add a shadow when the "header" is fixed.

```
    $('header').scrollToFixed( {
        fixed: function() { 
            $('header').addClass('header-shadow');
        },
        unfixed: function() { 
            $('header').removeClass('header-shadow');
        }
    });
```

**Comment by bigspotteddog** [comment]
Seems to be setting and removing the class. You might need to check your css for the shadow. Please see this example: http://jsfiddle.net/ZczEt/2572.

**Comment by estebandinamarca** [comment]
You are right, thanks for answer, but I think this is the problem:
When "header" is at the top, apply the "addClass" by default. 
Look this example: http://jsfiddle.net/ZczEt/2573/

I need apply "addClass" just when user start to scroll. Any solution?

**Comment by bigspotteddog** [comment]
Attach a listener to window.scroll. This is how the plugin does it.
